const initialData = {
    tasks: {
        'line-1': { id: 'line-1', content: 'I knew her for a little ghost', 'realOrder': 1, 'realStanza': 1 },
        'line-2': { id: 'line-2', content: 'That in my garden walked;', 'realOrder': 2, 'realStanza': 1 },
        'line-3': { id: 'line-3', content: 'The wall is high—higher than most—', 'realOrder': 3, 'realStanza': 1 },
        'line-4': { id: 'line-4', content: 'And the green gate was locked.', 'realOrder': 4, 'realStanza': 1 },
        'line-5': { id: 'line-5', content: 'And yet I did not think of that', 'realOrder': 1, 'realStanza': 2 },
        'line-6': { id: 'line-6', content: 'Till after she was gone—', 'realOrder': 2, 'realStanza': 2 },
        'line-7': { id: 'line-7', content: 'I knew her by the broad white hat,', 'realOrder': 3, 'realStanza': 2 },
        'line-8': { id: 'line-8', content: 'All ruffled, she had on.', 'realOrder': 4, 'realStanza': 2 },
        'line-9': { id: 'line-9', content: 'By the dear ruffles round her feet,', 'realOrder': 1, 'realStanza': 3 },
        'line-10': { id: 'line-10', content: 'By her small hands that hung', 'realOrder': 2, 'realStanza': 3 },
        'line-11': { id: 'line-11', content: 'In their lace mitts, austere and sweet,', 'realOrder': 3, 'realStanza': 3 },
        'line-12': { id: 'line-12', content: 'Her gown\'s white folds among.', 'realOrder': 4, 'realStanza': 3 },
        'line-13': { id: 'line-13', content: 'I watched to see if she would stay,', 'realOrder': 1, 'realStanza': 4 },
        'line-14': { id: 'line-14', content: 'What she would do—and oh!', 'realOrder': 2, 'realStanza': 4 },
        'line-15': { id: 'line-15', content: 'She looked as if she liked the way', 'realOrder': 3, 'realStanza': 4 },
        'line-16': { id: 'line-16', content: 'I let my garden grow!', 'realOrder': 4, 'realStanza': 4 },
        'line-17': { id: 'line-17', content: 'She bent above my favourite mint', 'realOrder': 1, 'realStanza': 5 },
        'line-18': { id: 'line-18', content: 'With conscious garden grace,', 'realOrder': 2, 'realStanza': 5 },
        'line-19': { id: 'line-19', content: 'She smiled and smiled—there was no hint', 'realOrder': 3, 'realStanza': 5 },
        'line-20': { id: 'line-20', content: 'Of sadness in her face.', 'realOrder': 4, 'realStanza': 5 },
        'line-21': { id: 'line-21', content: 'She held her gown on either side', 'realOrder': 1, 'realStanza': 6 },
        'line-22': { id: 'line-22', content: 'To let her slippers show,', 'realOrder': 2, 'realStanza': 6 },
        'line-23': { id: 'line-23', content: 'And up the walk she went with pride,', 'realOrder': 3, 'realStanza': 6 },
        'line-24': { id: 'line-24', content: 'The way great ladies go.', 'realOrder': 4, 'realStanza': 6 },
        'line-25': { id: 'line-25', content: 'And where the wall is built in new', 'realOrder': 1, 'realStanza': 7 },
        'line-26': { id: 'line-26', content: 'And is of ivy bare', 'realOrder': 2, 'realStanza': 7 },
        'line-27': { id: 'line-27', content: 'She paused—then opened and passed through', 'realOrder': 3, 'realStanza': 7 },
        'line-28': { id: 'line-28', content: 'A gate that once was there.', 'realOrder': 4, 'realStanza': 7 }
    },
    columns: {
        'stanza-1': {
            id: 'stanza-1',
            title: 'Stanza 1',
            taskIds: ['line-26',
                'line-1',
                'line-22',
                'line-16'],
        },
        'stanza-2': {
            id: 'stanza-2',
            title: 'Stanza 2',
            taskIds: ['line-5',
                'line-18',
                'line-4',
                'line-3'],
        },
        'stanza-3': {
            id: 'stanza-3',
            title: 'Stanza 3',
            taskIds: ['line-15',
                'line-24',
                'line-10',
                'line-17'],
        },
        'stanza-4': {
            id: 'stanza-4',
            title: 'Stanza 4',
            taskIds: ['line-13',
                'line-7',
                'line-27',
                'line-14'],
        },
        'stanza-5': {
            id: 'stanza-5',
            title: 'Stanza 5',
            taskIds: ['line-25',
                'line-2',
                'line-6',
                'line-12'],
        },
        'stanza-6': {
            id: 'stanza-6',
            title: 'Stanza 6',
            taskIds: ['line-23',
                'line-11',
                'line-28',
                'line-8'],
        },
        'stanza-7': {
            id: 'stanza-7',
            title: 'Stanza 7',
            taskIds: ['line-20',
                'line-21',
                'line-19',
                'line-9'],
        },
    },
    // Facilitate reordering of the columns
    columnOrder: ['stanza-1', 'stanza-2', 'stanza-3', 'stanza-4', 'stanza-5', 'stanza-6', 'stanza-7'],
};

export default initialData;
