trigger:
  branches:
    include:
    - master
name: 1.0.$(Rev:r)
variables:
- name: solution
  value: '**/*.sln'
- name: buildPlatform
  value: 'x64'
- name: buildConfiguration
  value: 'Release'
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: 'build'
        repository: 'summershalloween/summershalloween'
        Dockerfile: '$(system.defaultworkingdirectory)/SummersManorHalloweenPuzzle/Dockerfile.webapp'
        tags: |
          $(Build.BuildNumber)
          latest

    - task: Docker@2
      displayName: Tag image for Harbor
      inputs:
        command: 'tag'
        arguments: 'summershalloween/summershalloween:$(Build.BuildNumber) harbor.summershome.duckdns.org/summershalloween/summershalloween:$(Build.BuildNumber)'

    - task: Docker@2
      displayName: Tag latest for Harbor
      inputs:
        command: 'tag'
        arguments: 'summershalloween/summershalloween:latest harbor.summershome.duckdns.org/summershalloween/summershalloween:latest'

    - task: Docker@2
      displayName: Login to Harbor
      inputs:
        command: 'login'
        containerRegistry: 'Harbor Container Registry'

    - task: Docker@2
      displayName: Push image to Harbor
      inputs:
        command: 'push'
        repository: 'harbor.summershome.duckdns.org/summershalloween/summershalloween'
        tags: |
          $(Build.BuildNumber)
          latest
      retryCountOnTaskFailure: 3
      timeoutInMinutes: 15
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: '**/docker-compose.yml'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'