trigger:
  branches:
    include:
    - master
name: 1.0.$(Rev:r)
variables:
- name: solution
  value: '**/*.sln'
- name: buildPlatform
  value: 'x64'
- name: buildConfiguration
  value: 'Release'
stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    pool: Default
    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: 'build'
        repository: 'summershalloween/summershalloween'
        Dockerfile: '$(system.defaultworkingdirectory)/SummersManorHalloweenPuzzle/Dockerfile.webapp'
        tags: |
          $(Build.BuildNumber)
- stage: DEV
  displayName: Deploy To Dev
  jobs:
  - job: DeployToDev
    displayName: Deploy To Dev
    pool: Default
    steps:
    - task: Bash@3
      displayName: 'Test Harbor connectivity'
      inputs:
        targetType: 'inline'
        script: |
          ping -c 4 harbor.summershome.duckdns.org
              nslookup harbor.summershome.duckdns.org
              curl -I https://harbor.summershome.duckdns.org
    - task: Docker@2
      displayName: Tag image for Harbor
      inputs:
        command: 'tag'
        arguments: 'summershalloween/summershalloween:$(Build.BuildNumber) harbor.summershome.duckdns.org/summershalloween/summershalloween:dev.$(Build.BuildNumber)'
    - task: Docker@2
      displayName: Login to Harbor
      inputs:
        command: 'login'
        containerRegistry: 'Harbor Container Registry'
    - task: Docker@2
      displayName: Push image to Harbor
      inputs:
        command: 'push'
        containerRegistry: 'Harbor Container Registry'
        repository: 'summershalloween/summershalloween'
        tags: |
          dev.$(Build.BuildNumber)
- stage: PROD
  trigger: manual
  displayName: Deploy To Prod
  jobs:
  - job: DeployToProd
    displayName: Deploy To Prod
    pool: Default
    steps:
    - task: Bash@3
      displayName: 'Test Harbor connectivity'
      inputs:
        targetType: 'inline'
        script: |
          ping -c 4 harbor.summershome.duckdns.org
              nslookup harbor.summershome.duckdns.org
              curl -I https://harbor.summershome.duckdns.org
    - task: Docker@2
      displayName: Tag image for Harbor
      inputs:
        command: 'tag'
        arguments: 'summershalloween/summershalloween:$(Build.BuildNumber) harbor.summershome.duckdns.org/summershalloween/summershalloween:prod.$(Build.BuildNumber)'
    - task: Docker@2
      displayName: Login to Harbor
      inputs:
        command: 'login'
        containerRegistry: 'Harbor Container Registry'
    - task: Docker@2
      displayName: Push image to Harbor
      inputs:
        command: 'push'
        containerRegistry: 'Harbor Container Registry'
        repository: 'summershalloween/summershalloween'
        tags: |
          prod.$(Build.BuildNumber)