version: '3'
services:
  MySql:
    image: 'mysql:8.0.31-debian'
    environment:
     - MYSQL_ROOT_PASSWORD=Rpibbb013.
     - MYSQL_DATABASE=SummersManor
     - MYSQL_USER=WebAppUser
     - MYSQL_PASSWORD=Rpibbb013.
    ports:
     - "3306:3306"
     - "33060:33060"
  WebApp:
    image: forevercamaros/summershalloween:latest
    build:
      context: .
    environment:
     - CONNECTIONSTRING=Server=mysql;Database=SummersManor;User Id=WebAppUser;Password=Rpibbb013.;
    ports:
     - "80:80"
