version: '3'
name: summersmanorhalloween
services:
  mongo:
    image: mongo
    container_name: MongoDb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: webapp
      MONGO_INITDB_ROOT_PASSWORD: Rpibbb013
    ports:
    - "27017:27017"
  WebApp:
    image: forevercamaros/summershalloween:1.0.97
    container_name: WebApp
    restart: always
    ports:
     - "80:80"
     - "443:443"
