version: '3'
name: SummersManorHalloween
services:
  mongo:
    image: mongo
    container_name: MongoDb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: charlie
      MONGO_INITDB_ROOT_PASSWORD: Rpibbb013
  WebApp:
    image: forevercamaros/summershalloween:1.0.78
    container_name: WebApp
    restart: always
    ports:
     - "80:80"
     - "443:443"
