apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: halloween-web-app-dev

resources:
- ../../base
- ingress.yaml

images:
- name: nexus.summershome.duckdns.org/summershalloween/summershalloween
  newTag: dev.1.0.29
